# Generated by Django 4.1.2 on 2022-10-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='N/A'),
        ),
    ]
