# Generated by Django 4.1.2 on 2022-10-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img_url',
            field=models.CharField(default='#', max_length=128),
        ),
    ]
