# Generated by Django 4.1.2 on 2022-10-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_post_date_posted_post_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
